# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 10:54
from __future__ import unicode_literals

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_positive', models.BooleanField()),
                ('timezone_hours', models.SmallIntegerField()),
                ('timezone_minutes', models.SmallIntegerField()),
                ('mail_status', models.BooleanField(default=True)),
                ('dl_group', models.CharField(blank=True, max_length=70)),
                ('image', models.ImageField(upload_to=base.models.content_file_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
