# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, default=None, max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='blade',
            name='chassis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Chassis'),
        ),
        migrations.AddField(
            model_name='blade',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
